name: Build & Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    # branches:
    #   - master
    #   - dev

  # pull_request:
  #   branches:
  #     - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.ref_name }}

jobs:
  # test:
  #   timeout-minutes: 10
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     #      - name: Build containers
  #     #        run: docker compose build

  #     - name: Test backend
  #       run: docker compose run --build backend sh -c 'npx prisma migrate reset --force && export NODE_ENV=test && npx jest'

  push:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # needs: test
    # if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GIT_TOKEN}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build containers
        run: docker buildx build -f docker-compose.yml -f docker-compose.prod.yml --platform=linux/amd64,linux/arm64 --target production --push --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.TAG}} --cache-from=type=registry,ref=${{env.REGISTRY}}/${{env.IMAGE_NAME}}:buildcache --cache-to=type=registry,ref=${{env.REGISTRY}}/${{env.IMAGE_NAME}}:buildcache,mode=max

#      - name: Build and push Docker images
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#          #push: true
#          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}:buildcache
#          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}:buildcache,mode=max

#      - name: Add tag
#        run: docker tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.TAG}}

      # - name: Tag with Git SHA
      #   run: docker tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{github.sha}}

#      - name: Push to Docker Hub
#        run: |
#          docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.TAG}}
#          docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest